#pragma config(Motor,  port2,           left1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           left2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           arm2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           right2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           right1,        tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "CoryLib.h"

task main()
{
	//Define gearboxes and drivetrain
	tGearBox armGearBox;
	tGearBox leftSideGearBox;
	tGearBox rightSideGearBox;
	tDriveTrain robotDriveTrain;

	//Create gearboxes
	createGearBox(armGearBox, arm1, arm2);
	createGearBox(leftSideGearBox, left1, left2);
	createGearBox(rightSideGearBox, right1, right2);

	//Create drivetrain
	createDriveTrain(robotDriveTrain, leftSideGearBox, rightSideGearBox);

	while(true)
	{
		//Do arcade drive with joystick 3 as throttole, joystick 1 as wheel
		arcadeDrive(robotDriveTrain, vexRT[Ch3], vexRT[Ch1]);
		//Control arm using button 6U as up, and 6D as down at 100,-100 power
		buttonManipulate(armGearBox, vexRT[Btn6U], vexRT[Btn6D], 100, -100);
	}
}
